#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99
STOP=10
PROG=/usr/bin/homekit-chromecast
CONFIG=/etc/homekit-chromecast/config.yaml
start_service() {
    [ -x "$PROG" ] || return 1
    [ -r "$CONFIG" ] || return 1
    procd_open_instance
    procd_set_param command "$PROG" -config "$CONFIG" serve
    procd_set_param file "$CONFIG"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param term_timeout 10
    procd_close_instance
}
